# Generated by Django 3.2.6 on 2022-11-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='sketch_project_image',
            field=models.ImageField(default=1, upload_to='project_image', verbose_name='Architectural Design'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
