# Generated by Django 3.2.6 on 2022-11-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20221101_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sketch_project_image',
            field=models.ImageField(blank='', null=True, upload_to='project_image', verbose_name='Architectural Design'),
        ),
    ]
