# Generated by Django 3.2.6 on 2022-11-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_sketch_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='Your Budget Price for the Project', max_digits=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(help_text='Where is it located', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Your Project Name', max_length=255, verbose_name='project_name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(help_text='What type of project is it?', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='sketch_project_image',
            field=models.ImageField(blank='', help_text='Architectural Design Image for the Project', null=True, upload_to='project_image', verbose_name='Architectural Design'),
        ),
    ]
