# Generated by Django 3.2.6 on 2022-11-03 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20221101_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='project.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('user', 'project')},
        ),
    ]
