# Generated by Django 3.2.6 on 2022-11-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20221103_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
