# Generated by Django 3.2.6 on 2022-11-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_equipment_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together=set(),
        ),
    ]
